title: events.deaf.group
url: https://events.deaf.group
description: events.deaf.group
remote_theme: jekyll/minima #githubrepo

gems:
  - jekyll-seo-tag
  - jekyll-feed

plugins:
  - jekyll-remote-theme

collections:
  events:
    output: true
    permalink: /events/:path/
    title: Events